FROM almalinux:8
#RUN cd /tmp this command will not work to change the directory
# when we login it launch in the specified directory
WORKDIR /tmp
RUN echo "Hello Prakash" > greeting.txt
CMD [ "sleep", "120" ]