FROM almalinux:8
#combination of cmd and entrypoint can be used for best resutls, such as the container main job is to ping it wcannot be changed but the target webiste would be changed
CMD [ "bing.com" ]
ENTRYPOINT [ "ping"]